services:
  postgres:
    container_name: go-users-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ../..
      dockerfile: docker/build/Dockerfile-app
    container_name: go-users-app
    env_file:
      - ../../.env.prod
    ports:
      - "${HTTP_PORT}:8080"
    depends_on:
      migrations:
        condition: service_completed_successfully

volumes:
  postgres_data: